### ISSUE TITLE
Website down and run with meteor doesnt work

### ISSUE THREAD

**Issue by petrk94** [peer/mind#217]
Hello,

I just tried to run it, but, well meteor give a error message:
can you help?
Thanks 

```
$meteor
[[[[[ /var/www/virtual/xxxxx/peermind.xxxxx.de ]]]]]

=> Started proxy.
=> A patch (Meteor 1.6.1.4) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
api: updating npm dependencies -- mime-types...
/home/xxxxx/.meteor/packages/coffeescript/.1.11.1_3.15qetf5.4k85++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/var/www/virtual/xxxxx/peermind.xxxxx.de/packages/balancetext/vendor/jquery.balancetext.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at wrapper (/tools/fs/files.js:1558:35)
    at wrap.makeCacheKey (/tools/fs/optimistic.js:25:15)
    at Entry._reallyRecompute (/home/xxxxx/.meteor/packages/meteor-tool/.1.6.0_1.10s56dy.asfa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/home/xxxxx/.meteor/packages/meteor-tool/.1.6.0_1.10s56dy.asfa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/home/xxxxx/.meteor/packages/meteor-tool/.1.6.0_1.10s56dy.asfa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/home/xxxxx/.meteor/packages/meteor-tool/.1.6.0_1.10s56dy.asfa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at _.values.forEach.source (/tools/isobuild/compiler.js:558:22)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/compiler.js:494:21
    at files.withCache (/tools/isobuild/compiler.js:184:28)
    at Object.withCache (/tools/fs/files.js:1658:12)
    at /tools/isobuild/compiler.js:183:11
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/home/xxxxx/.meteor/packages/meteor-tool/.1.6.0_1.10s56dy.asfa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/tools/isobuild/compiler.js:178:5)
    at /tools/isobuild/isopack-cache.js:362:30
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:317:18)
    at Profile.time (/tools/isobuild/isopack-cache.js:251:16)
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:250:17
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:241:20)
    at /tools/isobuild/isopack-cache.js:77:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/xxxxx/.meteor/packages/meteor-tool/.1.6.0_1.10s56dy.asfa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at exports.PackageMap.eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:76:24)
    at /tools/project-context.js:847:25
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:846:18)
    at /tools/project-context.js:285:9
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:275:18)
    at Profile.run (/tools/project-context.js:267:12)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:266:13)
    at /tools/runners/run-app.js:554:29
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:553:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
    at AppRunner._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:408:12

```

**Comment by petrk94** [comment]
ok I this information from my hoster

Executable: /home/xxxxx/.meteor/packages/meteor-tool/.1.6.0_1.10s56dy.asfa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node 
working directory: /var/www/virtual/xxxxx/peermind.xxxxx.de

The problem is, that the software used more than 968 MB and got killed by the server management system :/

**Comment by mitar** [comment]
I suggest you remove `/home/xxxxx/.meteor` and reinstall Meteor again.

**Comment by mitar** [comment]
Do you use the Docker image?

**Comment by petrk94** [comment]
@mitar I try to remove .meteor
No, docker image is not possible on the hoster.

**Comment by mitar** [comment]
So did removing `.meteor `help? Is there some hard limit on disk space? Maybe what happens is that during building it hits it and cannot write necessary files?

If you cannot run Docker images, you could do that you locally build Meteor app using `meteor bundle` command and that will produce tgz for you, and then you can copy it over to the server. You have to do `npm install` there, but it might be overall smaller (no need for Meteor itself). See [here](https://guide.meteor.com/deployment.html#custom-deployment).

**Comment by petrk94** [comment]
why not providing a ready to use meteor app?

**Comment by mitar** [comment]
What do you mean? This is ready to use Meteor app. You have a problem that you have a disk space limit, so we are trying to find a workaround for this limit.

**Comment by petrk94** [comment]
@mitar
No no, the disc space is not the problem. The problem is that the memory, RAM, is has consuming too much, that's why the hoster has killed the application on my account. That's the Problem.

**Comment by mitar** [comment]
Aha. I understood that it is about the disk space.

Anyway, my recommendation is the same. Instead of using Meteor/PeerMind in development mode, which seems based on the error that you are doing, which takes a lot of memory and everything else because it does much more then just run the app, you should deploy the app. You can use Docker for that, or you can use any of other approaches to deploying a Meteor app I linked to you above. I think doing a proper deployment will help your case.

**Comment by mitar** [comment]
Production deployment. This means something you deploy for end-users which are then using the app. See [here](https://en.wikipedia.org/wiki/Deployment_environment#Production) for more information.

Yes, I understand that you cannot use Docker, so I linked you other ways you can use deploy Meteor app. Here is the link again: https://guide.meteor.com/deployment.html#custom-deployment

**Comment by petrk94** [comment]
@mitar I know what is production deployment, but I mean how to run peermind on my sharedhost without the meteor dev deploy?

**Comment by mitar** [comment]
I don't understand. Have you read the link I provided to you. It is written there how to do it.
